### ISSUE TITLE
could not read config file: open file:///etc/containerpilot.json: no such file or directory

### ISSUE THREAD

**Issue by hariprasathinvenzo** [PacktPublishing/PHP-Microservices#3]
Hi,

I have followed the steps and im able to run the images but its getting exited I checked the logs and i got the below error

could not read config file: open file:///etc/containerpilot.json: no such file or directory

**Comment by sonam-packt** [comment]
Hello @hariprasathinvenzo 
Can you please check and let me know that the error you are getting is from which chapter and if you can check that do you have file named "containerpilot.json" .
